//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dad_ViziteuMihai
{
    using dad_ViziteuMihai.Forms;
    using System;
    using System.Collections.Generic;
    
    public partial class Operatie
    {
        public Operatie()
        {
            //this.Rulaje = new HashSet<Rulaje>();
            this.Rulaje = new myColl<Rulaje>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Numar { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Doc { get; set; }
        public Nullable<System.DateTime> DataDoc { get; set; }
        public string Explicatie { get; set; }

        //public virtual ICollection<Rulaje> Rulaje { get; set; }
        public virtual myColl<Rulaje> Rulaje { get; set; }
    }
}
